fixes:
  - "pennylane_qchem/::qchem/pennylane_qchem/"
  - "/usr/share/miniconda/lib/python3.7/site-packages/::"

ignore:
  - "pennylane/devices/tests/*"

codecov:
    notify:
        after_n_builds: 6

comment:
    after_n_builds: 6
